name: Deploy Frontend

on:
  push:
    branches:
      - main  # Выполнять пайплайн при пуше в ветку main

jobs:
  deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Настройка AWS CLI
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-central-1
          aws s3 ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Шаг 3: Копирование фронтенда в S3
      - name: Deploy Frontend to S3
        run: |
          # Сначала исключаем config.json из удаления
          aws s3 sync ./frontend/templates s3://book-sales-platform-frontend --delete --exclude "config.json"
          # После этого отдельно синхронизируем config.json, чтобы он точно оставался актуальным
          aws s3 cp ./frontend/config.json s3://book-sales-platform-frontend/config.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Шаг 4: Очистка кеша CloudFront
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
